# patch-email.ps1
# Writes 4 email files verbatim via base64 (paste-proof).

$ErrorActionPreference = 'Stop'
cd C:\Users\kevch\Desktop\ProjectFortuna\vendorhub

$files = @{
  'src\lib\email\client.ts' = 'aW1wb3J0IHsgUmVzZW5kIH0gZnJvbSAicmVzZW5kIjsKCmNvbnN0IHJlc2VuZCA9IG5ldyBSZXNlbmQocHJvY2Vzcy5lbnYuUkVTRU5EX0FQSV9LRVkpOwoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHNlbmRFbWFpbChhcmdzOiB7CiAgdG86IHN0cmluZzsKICBzdWJqZWN0OiBzdHJpbmc7CiAgcmVhY3Q6IFJlYWN0LlJlYWN0RWxlbWVudDsKfSkgewogIGlmICghcHJvY2Vzcy5lbnYuUkVTRU5EX0FQSV9LRVkpIHsKICAgIGNvbnNvbGUud2FybigiW2VtYWlsXSBSRVNFTkRfQVBJX0tFWSBtaXNzaW5nIOKAlCBza2lwcGluZyBzZW5kIik7CiAgICByZXR1cm4geyBza2lwcGVkOiB0cnVlIH07CiAgfQogIGNvbnN0IGZyb20gPSBwcm9jZXNzLmVudi5FTUFJTF9GUk9NID8/ICJWZW5kb3JIdWIgPFtlbWFpbCBwcm90ZWN0ZWRdPiI7CiAgY29uc3QgeyBlcnJvciB9ID0gYXdhaXQgcmVzZW5kLmVtYWlscy5zZW5kKHsKICAgIGZyb20sCiAgICB0bzogYXJncy50bywKICAgIHN1YmplY3Q6IGFyZ3Muc3ViamVjdCwKICAgIHJlYWN0OiBhcmdzLnJlYWN0LAogIH0pOwogIGlmIChlcnJvcikgY29uc29sZS5lcnJvcigiW2VtYWlsXSBzZW5kIGZhaWxlZDoiLCBlcnJvcik7CiAgcmV0dXJuIHsgb2s6ICFlcnJvciB9Owp9Cg=='
  'src\lib\email\templates\offer-received.tsx' = 'ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gT2ZmZXJSZWNlaXZlZCh7CiAgYW1vdW50LCBsaXN0aW5nVGl0bGUsIGJ1eWVyTmFtZSwKfTogewogIGFtb3VudDogbnVtYmVyOyBsaXN0aW5nVGl0bGU6IHN0cmluZzsgYnV5ZXJOYW1lOiBzdHJpbmc7Cn0pIHsKICBjb25zdCB1cmwgPSAocHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfU0lURV9VUkwgPz8gImh0dHBzOi8vdmVuZG9yaHViLmNvLm56IikgKyAiL2FjY291bnQvb2ZmZXJzIjsKICByZXR1cm4gKAogICAgPGRpdiBzdHlsZT17eyBmb250RmFtaWx5OiAic3lzdGVtLXVpLCBzYW5zLXNlcmlmIiwgbWF4V2lkdGg6IDU2MCB9fT4KICAgICAgPGgxIHN0eWxlPXt7IGZvbnRTaXplOiAyMCB9fT5Zb3UgaGF2ZSBhIG5ldyBvZmZlcjwvaDE+CiAgICAgIDxwPkEgdmVyaWZpZWQgYnV5ZXIgaGFzIHN1Ym1pdHRlZCBhbiBvZmZlciBvZiA8c3Ryb25nPk5aJHthbW91bnQudG9Mb2NhbGVTdHJpbmcoKX08L3N0cm9uZz4gb246PC9wPgogICAgICA8YmxvY2txdW90ZSBzdHlsZT17eyBib3JkZXJMZWZ0OiAiM3B4IHNvbGlkICMxMGI5ODEiLCBwYWRkaW5nTGVmdDogMTIsIG1hcmdpbjogIjEycHggMCIgfX0+CiAgICAgICAge2xpc3RpbmdUaXRsZX0KICAgICAgPC9ibG9ja3F1b3RlPgogICAgICA8cD5TaWduIGluIHRvIFZlbmRvckh1YiB0byByZXZpZXcgb3IgcmVzcG9uZCB0byB7YnV5ZXJOYW1lfSZhcG9zO3Mgb2ZmZXIuPC9wPgogICAgICA8YSBocmVmPXt1cmx9CiAgICAgICAgIHN0eWxlPXt7IGJhY2tncm91bmQ6ICIjMTBiOTgxIiwgY29sb3I6ICJ3aGl0ZSIsIHBhZGRpbmc6ICIxMHB4IDE2cHgiLAogICAgICAgICAgICAgICAgICB0ZXh0RGVjb3JhdGlvbjogIm5vbmUiLCBib3JkZXJSYWRpdXM6IDYsIGRpc3BsYXk6ICJpbmxpbmUtYmxvY2siIH19PgogICAgICAgIFZpZXcgb2ZmZXIKICAgICAgPC9hPgogICAgPC9kaXY+CiAgKTsKfQo='
  'src\lib\email\templates\offer-accepted.tsx' = 'ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gT2ZmZXJBY2NlcHRlZCh7CiAgYW1vdW50LCBsaXN0aW5nVGl0bGUsCn06IHsKICBhbW91bnQ6IG51bWJlcjsgbGlzdGluZ1RpdGxlOiBzdHJpbmc7Cn0pIHsKICBjb25zdCB1cmwgPSAocHJvY2Vzcy5lbnYuTkVYVF9QVUJMSUNfU0lURV9VUkwgPz8gImh0dHBzOi8vdmVuZG9yaHViLmNvLm56IikgKyAiL2FjY291bnQvb2ZmZXJzIjsKICByZXR1cm4gKAogICAgPGRpdiBzdHlsZT17eyBmb250RmFtaWx5OiAic3lzdGVtLXVpLCBzYW5zLXNlcmlmIiwgbWF4V2lkdGg6IDU2MCB9fT4KICAgICAgPGgxIHN0eWxlPXt7IGZvbnRTaXplOiAyMCwgY29sb3I6ICIjMTBiOTgxIiB9fT5Zb3VyIG9mZmVyIHdhcyBhY2NlcHRlZDwvaDE+CiAgICAgIDxwPkdyZWF0IG5ld3Mg4oCUIHRoZSBzZWxsZXIgaGFzIGFjY2VwdGVkIHlvdXIgb2ZmZXIgb2YgPHN0cm9uZz5OWiR7YW1vdW50LnRvTG9jYWxlU3RyaW5nKCl9PC9zdHJvbmc+IG9uOjwvcD4KICAgICAgPGJsb2NrcXVvdGUgc3R5bGU9e3sgYm9yZGVyTGVmdDogIjNweCBzb2xpZCAjMTBiOTgxIiwgcGFkZGluZ0xlZnQ6IDEyLCBtYXJnaW46ICIxMnB4IDAiIH19PgogICAgICAgIHtsaXN0aW5nVGl0bGV9CiAgICAgIDwvYmxvY2txdW90ZT4KICAgICAgPHA+TmV4dCBzdGVwczogY29ubmVjdCB3aXRoIHRoZSBzZWxsZXIgdmlhIFZlbmRvckh1YiBtZXNzYWdpbmcgdG8gYXJyYW5nZSBjb250cmFjdCBleGNoYW5nZS48L3A+CiAgICAgIDxhIGhyZWY9e3VybH0KICAgICAgICAgc3R5bGU9e3sgYmFja2dyb3VuZDogIiMxMGI5ODEiLCBjb2xvcjogIndoaXRlIiwgcGFkZGluZzogIjEwcHggMTZweCIsCiAgICAgICAgICAgICAgICAgIHRleHREZWNvcmF0aW9uOiAibm9uZSIsIGJvcmRlclJhZGl1czogNiwgZGlzcGxheTogImlubGluZS1ibG9jayIgfX0+CiAgICAgICAgT3BlbiBWZW5kb3JIdWIKICAgICAgPC9hPgogICAgPC9kaXY+CiAgKTsKfQo='
  'src\lib\email\templates\verification-approved.tsx' = 'ZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gVmVyaWZpY2F0aW9uQXBwcm92ZWQoKSB7CiAgY29uc3QgdXJsID0gKHByb2Nlc3MuZW52Lk5FWFRfUFVCTElDX1NJVEVfVVJMID8/ICJodHRwczovL3ZlbmRvcmh1Yi5jby5ueiIpICsgIi9idXkiOwogIHJldHVybiAoCiAgICA8ZGl2IHN0eWxlPXt7IGZvbnRGYW1pbHk6ICJzeXN0ZW0tdWksIHNhbnMtc2VyaWYiLCBtYXhXaWR0aDogNTYwIH19PgogICAgICA8aDEgc3R5bGU9e3sgZm9udFNpemU6IDIwLCBjb2xvcjogIiMxMGI5ODEiIH19PllvdSZhcG9zO3JlIHZlcmlmaWVkICYjMTAwMDM7PC9oMT4KICAgICAgPHA+WW91ciBpZGVudGl0eSBoYXMgYmVlbiB2ZXJpZmllZC4gWW91IGNhbiBub3cgbWFrZSBvZmZlcnMgb24gYW55IFZlbmRvckh1YiBsaXN0aW5nLjwvcD4KICAgICAgPGEgaHJlZj17dXJsfQogICAgICAgICBzdHlsZT17eyBiYWNrZ3JvdW5kOiAiIzEwYjk4MSIsIGNvbG9yOiAid2hpdGUiLCBwYWRkaW5nOiAiMTBweCAxNnB4IiwKICAgICAgICAgICAgICAgICAgdGV4dERlY29yYXRpb246ICJub25lIiwgYm9yZGVyUmFkaXVzOiA2LCBkaXNwbGF5OiAiaW5saW5lLWJsb2NrIiB9fT4KICAgICAgICBCcm93c2UgbGlzdGluZ3MKICAgICAgPC9hPgogICAgPC9kaXY+CiAgKTsKfQo='
}

foreach ($entry in $files.GetEnumerator()) {
  $path = $entry.Key
  $b64 = $entry.Value
  $content = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64))
  $dir = [System.IO.Path]::GetDirectoryName($path)
  if ($dir -and -not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  Set-Content -LiteralPath $path -Value $content -Encoding UTF8 -NoNewline
  $size = (Get-Item -LiteralPath $path).Length
  Write-Host "Wrote $path ($size bytes)" -ForegroundColor Green
}

Write-Host ''
Write-Host 'All 4 email files written.' -ForegroundColor Cyan